Feature/pl 2393 brukere med uttak
navikt/pensjon-selvbetjening-opptjening-frontend pull request #19
Opened 2021-03-08 11:13 UTC by rittikdey

2021-03-08 13:40 UTC, espengjostol requested changes

2021-03-08 13:40 UTC, espengjostol commented on public/locales/nn/translation.json
> +    "opptjening-details-uttak-text": "Ved uttak reduseres pensjonsbehaldningen din med like stor andel som uttaksgraden du har valgt.",
pensjonsbehaldningen din -> pensjonsbehaldninga di

2021-03-08 13:40 UTC, espengjostol commented on public/locales/nn/translation.json
> +    "opptjening-details-gradert-uttak-text": "Fordi du har gradert uttak har den nye oppteninga blitt lagt til pensjonsbehaldningen din.",
pensjonsbehaldningen din -> pensjonsbehaldninga di

2021-03-08 13:40 UTC, espengjostol commented on public/locales/nn/translation.json
> +    "opptjening-details-omsorgsopptjening-text": "Du hadde omsorgsopptjening i {{year}}, men siden den var mindre enn inntekten er den ikke en del av opptjeningsgrunnlaget.",
omsorgsopptjening -> omsorgsopptening, ikke -> ikkje, en del -> ein del, opptjeningsgrunnlaget -> oppteningsgrunnlaget

2021-03-08 13:40 UTC, espengjostol commented on public/locales/nb/translation.json
> +    "overfore-omsorgsopptjening-text": "Du har et eller flere år med omsorgsopptjening, og kan overføre dette til den andre av barnets foresatte her.",
et -> ett

2021-03-08 13:40 UTC, espengjostol commented on public/locales/nb/translation.json
> +    "opptjening-details-ingen-pensjonspoeng": "Det er ikke registrert noe pensjonspoeng dette året.",
noe -> noen

2021-03-08 13:40 UTC, espengjostol commented on public/locales/en/translation.json
> +    "overfore-omsorgsopptjening-text": "Du har et eller flere år med omsorgsopptjening, og kan overføre dette til den andre av barnets foresatte her.",
et -> ett

2021-03-08 13:40 UTC, espengjostol commented on public/locales/en/translation.json
> +    "opptjening-details-ingen-pensjonspoeng": "There is no registered pension points this year.",
is -> are

2021-03-08 13:40 UTC, espengjostol commented on public/locales/nn/translation.json
> +    "overfore-omsorgsopptjening-text": "Du har et eller flere år med omsorgsopptjening, og kan overføre dette til den andre av barnets foresatte her.",
et eller flere år med omsorgsopptjening -> eitt eller fleire år med omsorgsopptening

2021-03-08 13:52 UTC, rittikdey commented on public/locales/en/translation.json
> +    "opptjening-details-ingen-pensjonspoeng": "There is no registered pension points this year.",
fikset

2021-03-08 13:53 UTC, rittikdey commented on public/locales/en/translation.json
> +    "overfore-omsorgsopptjening-text": "Du har et eller flere år med omsorgsopptjening, og kan overføre dette til den andre av barnets foresatte her.",
Ikke oversatt enda - har bare kopiert inn norsk tekst

2021-03-08 13:53 UTC, rittikdey commented on public/locales/nb/translation.json
> +    "opptjening-details-ingen-pensjonspoeng": "Det er ikke registrert noe pensjonspoeng dette året.",
Fikset

2021-03-08 13:53 UTC, rittikdey commented on public/locales/nb/translation.json
> +    "overfore-omsorgsopptjening-text": "Du har et eller flere år med omsorgsopptjening, og kan overføre dette til den andre av barnets foresatte her.",
Fikset

2021-03-08 13:54 UTC, rittikdey commented on public/locales/nn/translation.json
> +    "opptjening-details-gradert-uttak-text": "Fordi du har gradert uttak har den nye oppteninga blitt lagt til pensjonsbehaldningen din.",
Fikset - nye tekster på nynorsk ikke kvalitetssikret enda

2021-03-08 13:54 UTC, rittikdey commented on public/locales/nn/translation.json
> +    "opptjening-details-uttak-text": "Ved uttak reduseres pensjonsbehaldningen din med like stor andel som uttaksgraden du har valgt.",
Fikset - nye tekster på nynorsk ikke kvalitetssikret enda

2021-03-08 13:55 UTC, rittikdey commented on public/locales/nn/translation.json
> +    "opptjening-details-omsorgsopptjening-text": "Du hadde omsorgsopptjening i {{year}}, men siden den var mindre enn inntekten er den ikke en del av opptjeningsgrunnlaget.",
Fikset - nye tekster på nynorsk ikke kvalitetssikret enda

2021-03-08 13:55 UTC, rittikdey commented on public/locales/nn/translation.json
> +    "overfore-omsorgsopptjening-text": "Du har et eller flere år med omsorgsopptjening, og kan overføre dette til den andre av barnets foresatte her.",
Fikset - nye tekster på nynorsk ikke kvalitetssikret enda

2021-03-09 07:29 UTC, espengjostol requested changes

2021-03-09 07:29 UTC, espengjostol commented on public/locales/en/translation.json
> +    "opptjening-details-ingen-pensjonsbeholdning": "There are no registered accumulated pension this year. This is because you did not have any income in {{year}}",
Her skal det fortsatt være "is" . Det var bare i neste linje det var flertall.

2021-03-09 10:27 UTC, espengjostol approved these changes

2021-03-11 09:54 UTC, merged